#!/usr/bin/env python3
"""Export confirmed pubs from mart_pub_locations for the Leaflet map.

Reads the pipeline DuckDB file (yahtzee.duckdb at the repo root) and writes:

  dashboard/pub_map/pubs.geojson   GeoJSON FeatureCollection
  dashboard/pub_map/pubs.js        same data as window.PUB_MAP_DATA (file:// safe)

Run after `bruin run` whenever seed_pubs / raw_pub_visits / geocoding change:

  python3 dashboard/scripts/export_pub_map.py
  python3 dashboard/scripts/export_pub_map.py --db /path/to/yahtzee.duckdb

Requires: pip install duckdb
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DB = REPO_ROOT / "yahtzee.duckdb"
OUT_DIR = REPO_ROOT / "dashboard" / "pub_map"
LONDON_CENTER = (-0.1278, 51.5074)


def _connect(db_path: Path):
    try:
        import duckdb
    except ImportError as exc:
        raise SystemExit(
            "duckdb is required to export the pub map.\n"
            "  pip install duckdb\n"
            "or: pip install -r assets/python/requirements.txt"
        ) from exc
    if not db_path.exists():
        raise SystemExit(f"DuckDB file not found: {db_path}")
    return duckdb.connect(str(db_path), read_only=True)


def _table_columns(con, table: str) -> set[str]:
    rows = con.execute(
        "select lower(column_name) from information_schema.columns "
        "where lower(table_name) = lower(?)",
        [table],
    ).fetchall()
    return {r[0] for r in rows}


def load_confirmed_pubs(con) -> list[dict]:
    cols = _table_columns(con, "mart_pub_locations")
    if not cols:
        raise SystemExit(
            "mart_pub_locations is missing — run `bruin run` first "
            "(OFFLINE_TEST=1 is fine)."
        )

    visit_expr = (
        "coalesce(visit_count, 1)::integer"
        if "visit_count" in cols
        else "1::integer"
    )
    merged_expr = "merged_from" if "merged_from" in cols else "NULL"
    sql = f"""
        select
            coalesce(pub_name, merchant_name_raw) as name,
            merchant_name_raw,
            lat::double as lat,
            lng::double as lng,
            source,
            {visit_expr} as visit_count,
            {merged_expr} as merged_from
        from mart_pub_locations
        where is_confirmed_pub
          and lat is not null
          and lng is not null
        order by visit_count desc, name
    """
    rows = con.execute(sql).fetchdf()
    pubs = []
    for rec in rows.to_dict(orient="records"):
        pubs.append(
            {
                "name": rec["name"],
                "merchant_name_raw": rec["merchant_name_raw"],
                "lat": float(rec["lat"]),
                "lng": float(rec["lng"]),
                "source": rec.get("source"),
                "visit_count": int(rec["visit_count"] or 1),
                "merged_from": rec.get("merged_from"),
            }
        )
    return pubs


def to_feature_collection(pubs: list[dict]) -> dict:
    features = []
    for pub in pubs:
        props = {
            "name": pub["name"],
            "merchant_name_raw": pub["merchant_name_raw"],
            "source": pub["source"],
            "visit_count": pub["visit_count"],
        }
        if pub.get("merged_from"):
            props["merged_from"] = pub["merged_from"]
        features.append(
            {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [pub["lng"], pub["lat"]],
                },
                "properties": props,
            }
        )
    return {
        "type": "FeatureCollection",
        "features": features,
        "metadata": {
            "grain": "mart_pub_locations (standalone — not joined to games)",
            "default_center": {"lng": LONDON_CENTER[0], "lat": LONDON_CENTER[1]},
            "confirmed_pub_count": len(features),
        },
    }


def write_outputs(collection: dict) -> tuple[Path, Path]:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    geojson_path = OUT_DIR / "pubs.geojson"
    js_path = OUT_DIR / "pubs.js"
    payload = json.dumps(collection, indent=2, ensure_ascii=False)
    geojson_path.write_text(payload + "\n", encoding="utf-8")
    js_path.write_text(
        "// Generated by dashboard/scripts/export_pub_map.py — do not edit.\n"
        "window.PUB_MAP_DATA = "
        + payload
        + ";\n",
        encoding="utf-8",
    )
    return geojson_path, js_path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--db",
        type=Path,
        default=DEFAULT_DB,
        help=f"DuckDB path (default: {DEFAULT_DB})",
    )
    args = parser.parse_args()

    con = _connect(args.db)
    try:
        pubs = load_confirmed_pubs(con)
    finally:
        con.close()

    collection = to_feature_collection(pubs)
    geojson_path, js_path = write_outputs(collection)
    print(
        f"Exported {len(pubs)} confirmed pub(s)\n"
        f"  {geojson_path.relative_to(REPO_ROOT)}\n"
        f"  {js_path.relative_to(REPO_ROOT)}"
    )
    if not pubs:
        print("No confirmed pubs with coordinates — add seed_pubs rows and re-run.")


if __name__ == "__main__":
    main()
